name: Sync Theme
on:
  push:
    paths:
      - 'themes/nicesima/**'
      - '.github/workflows/sync_theme.yml'
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: false
        fetch-depth: 0

    - uses: nxtlvlsoftware/git-subtree-action@1.1
      with:
        repo: 'icyleaf/hugo-theme-nicesima'
        path: 'themes/nicesima'
        deploy_key: ${{ secrets.SSH_DEPLOY_KEY }}
        branch: main
        force: true # will force push to the downstream repository
